---
- name: Set if installed php facts
  set_fact:
    installed_prefix: "{{ lookup('pipe',php_config_path + ' --prefix') }}"
    installed_php_version: "{{ lookup('pipe',php_config_path + ' --version') }}"
  when: is_php_installed

- name: Set if installed php facts
  set_fact:
    php_slowlog_path: "{{ installed_prefix + '/log/php-fpm.log.slow' }}"
  when: is_php_installed

- name: Set php version
  set_fact:
    real_php_version: "{{ installed_php_version is defined and php_version_param }}"

- debug:
    msg: "{{ real_php_version }}"

- debug:
    msg: "{{ php_version_param }}"

- name: Set php version
  set_fact:
    php_short_version: "{{ real_php_version.split('.')[0] }}.{{ real_php_version.split('.')[1] }}"

- name: Set process.dumpable available
  set_fact:
    dumpable_available: True
  when: (php_short_version == '7.0' and (real_php_version is version('7.0.29', '>='))) or
        (php_short_version == '7.1' and (real_php_version is version('7.1.17', '>='))) or
        (php_short_version == '7.2' and (real_php_version is version('7.2.5', '>='))) or
        (real_php_version is version('7.3', '>='))
