---
- name: PM values check
  assert:
    that: pool.pm.strategy in ['static', 'ondemand', 'dynamic']
    msg: "'pm.strategy' must be in ['static', 'ondemand', 'dynamic']"

- name: Process priority check
  assert:
    that:
      - pool.process.priority >= -19
      - pool.process.priority <= 20
    msg: "'pool.process.priority' must be great or equal -19 and less or equal 20"
  when:
    - pool.process.priority is defined